import random

sentence_data = [
    ("Take a Shot!", 25),
    ("Gift a Shot", 15),
    ("Everybody but you drinks!", 8),
    ("Everybody takes a Shot!", 10),
    (f"Take {random.randint(1,10)}x Shots!", 4),
    (f"Gift {random.randint(1,10)}x Shots!", 4),
    ("REVENGE, Spin yourself 10x Times!", 5),
    ("All girls must drink", 8),
    ("All guys drink", 8),
    ("Choose someone to drink with you. He/she, your drinking buddy, should always drink with you", 5),
    ("You can make up any rule that everyone has to follow, such as you can only drink with your left hand. Everyone (including you) must follow this rule for the whole entire game and if you disobey you must drink.", 2),
    ("Recite a tongue twister flawlessly or take a shot!", 7),
    ("Tell a funny joke. If no one laughs, you take a shot!", 6),
    ("Pick someone to be your 'partner in crime.' Whenever one of you drinks, the other must too.", 4),
    ("Share an embarrassing story from your past or take a shot!", 6),
    ("Play a round of 'Rock, Paper, Scissors' with the person to your left. Loser takes a shot!", 5),
    ("Name three different types of cocktails in 10 seconds or take a shot!", 6),
    ("If you've ever been to [specific place], take a shot!", 3),
    ("Share your most recent social media post or take a shot!", 4),
    ("Choose a word. Everyone must say a sentence that includes that word. If someone fails, they drink.", 5),
    ("If you've ever done a handstand, take a shot!", 3),
    ("Pick someone to be your 'water carrier.' Whenever you take a shot, they must take one too.", 4),
    ("Share a cringe-worthy pickup line or take a shot!", 5),
    ("If you've ever binge-watched a TV show, take a shot!", 4),
    ("Everyone wearing black takes a shot!", 3),
    ("Share your most embarrassing moment from high school or take a shot!", 5),
    ("If you've ever sung karaoke, take a shot!", 4),
    ("Tell a two truths and a lie. If someone guesses wrong, they take a shot!", 6),
    ("If you've ever stayed up all night, take a shot!", 4),
    ("The youngest player takes a shot!", 3),
    ("Share your guilty pleasure song. If someone else likes it too, you're safe. If not, you take a shot!", 6),
    ("If you've ever gotten a tattoo, take a shot!", 3),
    ("Share your favorite type of alcohol. If no one else likes it, you take a shot!", 5),
    ("The person with the most keys in their pocket takes a shot!", 4),
    ("If you've ever forgotten someone's birthday, take a shot!", 3),
    ("Share a photo you've taken in the last week or take a shot!", 4),
    ("Choose someone to be your 'dance partner.' Whenever the music plays, you both have to dance. If one of you stops, you both take a shot.", 5),
    ("Name a country starting with the last letter of your name. If you can't, take a shot!", 5),
    ("If you've ever sent a text to the wrong person, take a shot!", 4),
    ("Choose someone to be your 'rival.' Whenever one of you drinks, the other must drink too.", 4),
    ("If you've ever eaten something off the floor, take a shot!", 3),
    ("Share your most embarrassing moment from work or take a shot!", 5),
    ("The tallest player takes a shot!", 3),
    ("If you've ever worn mismatched shoes, take a shot!", 3),
    ("Everyone with a birthday in the current month takes a shot!", 4),
    ("Share your favorite childhood game. If no one else has played it, you take a shot!", 5),
    ("Choose someone to be your 'truth buddy.' Whenever you answer a truth question, they must answer one too.", 4),
    ("If you've ever tried a food and hated it, take a shot!", 3),
    ("Share the last photo you took. If no one else has a similar photo, you take a shot!", 4),
    ("The person with the longest hair takes a shot!", 3),
    ("If you've ever been skydiving, take a shot!", 3),
    ("Choose someone to be your 'cheers partner.' Whenever you raise your glass, they must raise theirs too.", 4),
    ("If you've ever sung in the shower, take a shot!", 4),
    ("Share a nickname you've been called. If someone else has been called the same thing, you're safe. If not, you take a shot!", 5),
    ("The person who last traveled by plane takes a shot!", 4),
    ("If you've ever won a contest or competition, take a shot!", 3),
    ("Choose a celebrity. If someone can't name a movie or song they've been in, they take a shot!", 5),
    ("If you've ever laughed so hard you cried, take a shot!", 4),
    ("Share a screenshot of your last text conversation. If someone has a funnier one, you take a shot!", 5),
    ("The person with the most unread messages takes a shot!", 4),
    ("If you've ever locked yourself out of your house, take a shot!", 3),
    ("Choose someone to be your 'partner in trivia.' If either of you answers a trivia question wrong, you both take a shot.", 5),
    ("Share a cringeworthy pickup line in a foreign language or take a shot!", 5),
    ("Choose a word. Everyone must come up with a song that includes that word in the lyrics. If someone can't, they take a shot!", 6),
    ("If you've ever prank-called someone, take a shot!", 4),
    ("Share a screenshot of your most used app. If someone else uses it more, you take a shot!", 5),
    ("Choose someone to be your 'dance-off opponent.' Each of you dances, and the group votes on the winner. The loser takes a shot.", 5),
    ("If you've ever forgotten someone's name right after being introduced, take a shot!", 4),
    ("Share your most embarrassing moment from a family gathering or take a shot!", 5),
    ("Choose a song. Everyone takes turns singing one line. If someone messes up, they drink.", 6),
    ("If you've ever dyed your hair a crazy color, take a shot!", 3),
    ("Share the last thing you searched for on the internet. If someone has a weirder search, you take a shot!", 5),
    ("If you've ever gotten lost in a familiar place, take a shot!", 3),
    ("Share your favorite meme. If no one else finds it funny, you take a shot!", 5),
    ("If you've ever pretended to be sick to get out of something, take a shot!", 4),
    ("Share the last text you received. If someone else has a funnier one, you take a shot!", 5),
    ("If you've ever eaten something out of the trash, take a shot!", 3),
    ("Share a picture of the contents of your fridge. If someone has weirder items, you take a shot!", 5),
    ("If you've ever used someone else's toothbrush, take a shot!", 3),
    ("Share a story of getting caught in a lie. If someone has a crazier story, you take a shot!", 5),
    ("Choose a number between 1 and 10. If no one else picks the same number, you take a shot!", 4),
    ("Share the last text message you received from a family member. If someone has a more embarrassing one, you take a shot!", 4),
    ("If you've ever been in a long-distance relationship, take a shot!", 3),
    ("Share the most embarrassing photo on your phone. If someone has a more embarrassing one, you take a shot!", 4),
    ("If you've ever fallen asleep in a movie theater, take a shot!", 3),
    ("Share your most embarrassing moment from a date. If someone has a worse date story, you take a shot!", 4),
    ("Choose a famous movie quote. Everyone takes turns saying it in the most dramatic way possible. If someone fails, they drink.", 3),
    ("If you've ever sent a text message to the wrong person, take a shot!", 4),
    ("Choose a color. Everyone wearing that color takes a shot!", 3),
    ("Share the most embarrassing thing in your search history. If someone has something worse, you take a shot!", 4),
    ("If you've ever locked yourself out of your house, take a shot!", 3),
    ("Share your favorite meme. If no one else finds it funny, you take a shot!", 4),
    ("If you've ever pretended to be sick to get out of something, take a shot!", 4),
    ("Share the last text you received from a friend. If someone else has a funnier one, you take a shot!", 5),
    ("If you've ever eaten something out of the trash, take a shot!", 3),
    ("Choose a famous landmark. If someone can't name its location, they take a shot!", 5),
    ("Share the most embarrassing thing in your camera roll. If someone has something more embarrassing, you take a shot!", 4),
    ("If you've ever been on a blind date, take a shot!", 3),
    ("Share the last embarrassing autocorrect fail in your text messages. If someone has a worse one, you take a shot!", 5),
    ("If you've ever ghosted someone, take a shot!", 4),
    ("Share your most embarrassing childhood photo. If someone has a more embarrassing one, you take a shot!", 5),
    ("Choose a famous quote. Everyone takes turns attributing it to the wrong person. If someone messes up, they drink.", 5),
    ("If you've ever accidentally sent a text to your boss that was meant for someone else, take a shot!", 4),
    ("Share the most embarrassing song on your playlist. If someone has a more embarrassing one, you take a shot!", 4),
    ("If you've ever been late to an important event, take a shot!", 3),
    ("Share the last embarrassing video you watched on the internet. If someone has seen a more embarrassing one, you take a shot!", 5),
    ("If you've ever sent a text message to the wrong group chat, take a shot!", 4),
    ("Share your most embarrassing moment from a school presentation. If someone has a worse presentation story, you take a shot!", 5),
    ("Choose a movie. Everyone takes turns reciting a famous line from that movie. If someone messes up, they drink.", 5),
    ("If you've ever forgotten someone's birthday and had to make up an excuse, take a shot!", 4),
    ("Share the most embarrassing thing you've Googled recently. If someone has a more embarrassing search, you take a shot!", 4),
    ("If you've ever accidentally liked an old social media post while stalking someone, take a shot!", 4),
    ("Share the last embarrassing autocorrect fail in your text messages. If someone has a worse one, you take a shot!", 5),
    ("If you've ever been caught in a lie by your parents, take a shot!", 4),
    ("Share the most embarrassing outfit you've worn in public. If someone has worn something more embarrassing, you take a shot!", 5),
    ("Choose a famous quote. Everyone takes turns attributing it to the wrong historical figure. If someone messes up, they drink.", 5),
    ("If you've ever accidentally sent a text message to your ex, take a shot!", 4),
    ("Share your most embarrassing childhood story. If someone has a more embarrassing one, you take a shot!", 4),
    ("If you've ever forgotten an anniversary, take a shot!", 4),
    ("Share the last embarrassing video you recorded on your phone. If someone has a more embarrassing video, you take a shot!", 5),
    ("If you've ever received a funny or awkward text message from your boss, take a shot!", 4),
    ("Share your most embarrassing moment from a family reunion. If someone has a worse family reunion story, you take a shot!", 5),
    ("Choose a famous movie scene. Everyone takes turns reenacting a line or moment from that scene. If someone messes up, they drink.", 6),
    ("If you've ever sent a text message meant for your significant other to someone else, take a shot!", 4),
    ("Share your most embarrassing moment from a work meeting. If someone has a worse work meeting story, you take a shot!", 5),
    ("If you've ever accidentally replied to a work email with a personal message, take a shot!", 4),
    ("Share the most embarrassing app on your phone. If someone has a more embarrassing app, you take a shot!", 5),
    ("If you've ever laughed uncontrollably during a serious moment, take a shot!", 4),
    ("Share the last cringe-worthy text message you received. If someone has a more cringe-worthy message, you take a shot!", 5),
    ("Choose a famous quote. Everyone takes turns attributing it to the wrong movie. If someone messes up, they drink.", 5),
    ("If you've ever accidentally pocket-dialed someone and had them hear something embarrassing, take a shot!", 4)
]
